### ISSUE TITLE
Great Package

### ISSUE THREAD

**Issue by zachcp** [bene200/msaR#1]
Hi Benedict,

I recently stumbled across msa.js and was thinking about packaging it up for R. Then I check Github and, what do you know, you've already done it! Awesome. I am interested in using msaR as a widget during a bioinformatic workflow that relies heavily on Bioconductor. I would be interested in seeing msaR packaged for Bioconductor/CRAN as i think it would be generally useful and much more visible. I am happy to help in any capacity.  

zach cp

**Comment by benediktrauscher** [comment]
Hi zach cp,

sorry for taking so long to get back to you - this issue kind of went under my radar! 
I agree that it would be cool to have the MSA viewer on Bioconductor. The problem for me is that at the moment I am a bit short on time and packaging up software for Bioconductor requires many additional things like automated tests, vignettes, etc (which I believe is a good thing). 
However if you would like to make an effort to package msaR up for Bioconductor I would be happy to assist in any way I can.

Best
Benedikt

**Comment by zachcp** [comment]
Yeah, I know it does take a bit of time. I will take over the project, add some features I want and a bit of documentation. Ideally It would get to BioC or CRAN so that it could be imported. If you like you can keep an eye on my fork and I'll keep you posted if/when I submit.

Thanks,
zach cp

**Comment by benediktrauscher** [comment]
Awesome! I'll be sure to check out your fork.

Thanks
Benedikt
